<?php

$this->device_types['MobilePAW'] = array(
    'TITLE'=>'Gadget PAWII',
    'PARENT_CLASS'=>'SDevices',
    'CLASS'=>'SGadgetPAW',
    'DESCRIPTION'=>'Gadget devices PAWII',
    'PROPERTIES'=>array(
        'namePAW'=>array('DESCRIPTION'=>'Топик + Имя устройства как на устройстве PAW/RMX3430 ','_CONFIG_TYPE'=>'text','_CONFIG_DEFAULT' => 'PAW/RMX3430'),
        'ip'=>array('DESCRIPTION'=>'Адрес','_CONFIG_TYPE'=>'text','_CONFIG_DEFAULT' => '192.168.1.1'),
        'port'=>array('DESCRIPTION'=>'Порт','_CONFIG_TYPE'=>'text','_CONFIG_DEFAULT' => 2323),
        'msgLevel'=>array('DESCRIPTION'=>'Уровень сообщений','_CONFIG_TYPE'=>'num','_CONFIG_DEFAULT' => 1,'_CONFIG_HELP'=>'SdTher'),
        'mqtt'=>array('DESCRIPTION'=>' ','_CONFIG_TYPE'=>'num','DATA_KEY'=>1,'_CONFIG_DEFAULT' => 1),
//        'registerEvent_status'=>array('DESCRIPTION'=>'Включить трансляцию в registerEvent (0-1)','_CONFIG_TYPE'=>'num'),
//        'registerProperties_status'=>array('DESCRIPTION'=>'Записывать свойства (0-1)','_CONFIG_TYPE'=>'num'),
//        'registerTelegram_status'=>array('DESCRIPTION'=>'Включить трансляцию в Telegram (0-1)','_CONFIG_TYPE'=>'num'),
        'customCMJ'=>array('DESCRIPTION'=>'Управление устройством через GET или MQTT прим. {"comm":"displayBrightness","param":"255"}','ONCHANGE'=>'comm','_CONFIG_TYPE'=>'text'),
//        'all_devices_tts_request'=>array('DESCRIPTION'=>'Также в основной ветки есть /all_devices/  в данной ветке находятся топики на которые подписываются все устройства, что позволяет управлять всеми устройствами сразу.','ONCHANGE'=>'ttsRequestAll'),
//        'comm_audio_alarm'=>array('DESCRIPTION'=>'Громкость будильника 0-7 (alarm)'),registerProperties_status
//        'comm_audio_music'=>array('DESCRIPTION'=>'Громкость медиа 0-15 (music)'),
//        'comm_audio_notification'=>array('DESCRIPTION'=>'Громкость notification 0-7 (notification)'),
//        'comm_audio_ring'=>array('DESCRIPTION'=>'Громкость рингтон 0-7 (ring)'),
//        'comm_audio_system'=>array('DESCRIPTION'=>'Громкость системная 0-7 (system)'),
//        'comm_audio_voice'=>array('DESCRIPTION'=>'Громкость разговора 0-5 (voice)'),
//        'comm_call_end'=>array('DESCRIPTION'=>'Отклонить вызов [логическое] Завершить разговор'),
//        'comm_call_number'=>array('DESCRIPTION'=>'Позвонить по номеру [номер]','ONCHANGE'=>'callNumber'),
//        'comm_display_brightness'=>array('DESCRIPTION'=>'Уровень яркости подсветки от 4 до 100 [число]','_CONFIG_TYPE'=>'num'),
//        'comm_display_mode'=>array('DESCRIPTION'=>'Тип подсветки','_CONFIG_TYPE'=>'select','_CONFIG_OPTIONS'=>'auto=Автоматический,manual=Ручной'),
//        'comm_display_timeOff'=>array('DESCRIPTION'=>'Установите время подсветки [число] (сек)','_CONFIG_TYPE'=>'num'),
//        'comm_display_toWake'=>array('DESCRIPTION'=>'Вывести устройство из спящего режима [логическое] 0/1','_CONFIG_TYPE'=>'num'),
//        'comm_notification_alert'=>array('DESCRIPTION'=>'Отправить уведомление на устройство {"alert":"Turn the lights off?", "title":"Light", "negative":"No", "positive":"Yes",  "neutral":"Neutral", "sound":"true", "id":2}'),
//        'comm_notification_create'=>array('DESCRIPTION'=>'Создать alert dialog, это окно с предупреждением которое вы можете конфигурировать на ваше усмотрение {"noti":"Any text", "title":"Title 2", "info":"Any text", "vibrate":true, "sound":true, "light":true, "id":2}'),
//        'comm_notification_delete'=>array('DESCRIPTION'=>'Удалить все уведомления'),
//        'comm_other_home'=>array('DESCRIPTION'=>'Перейти на главный экран [логическое]'),
//        'comm_other_openURL'=>array('DESCRIPTION'=>'Открыть URL в браузере [строка] http://ya.ru'),
//        'comm_other_play'=>array('DESCRIPTION'=>'Воспроизвести мелодию уведомления [логическое]'),
//        'comm_other_vibrate'=>array('DESCRIPTION'=>'Включить вибрацию, время в секундах [число] (1000 = 1сек)','_CONFIG_TYPE'=>'num'),
//        'comm_tts_request'=>array('DESCRIPTION'=>'Отправить текст в речь [строка]','_CONFIG_TYPE'=>'text'),
//        'comm_tts_stop'=>array('DESCRIPTION'=>'Остановить речь [логическое]','_CONFIG_TYPE'=>'num'),
//        'info_alert_response'=>array('DESCRIPTION'=>'Ответ от «диалогов» приходит в JSON формате и публикуется в топике /info/alert/response','_CONFIG_HELP'=>'SdThermostat'),
        'info_audio_alarm'=>array('DESCRIPTION'=>'Громкость будильника 0-7 (alarm)','_CONFIG_TYPE'=>'num'),
        'info_audio_music'=>array('DESCRIPTION'=>'Громкость медиа и игры 0-15 (music)','_CONFIG_TYPE'=>'num'),
        'info_audio_notification'=>array('DESCRIPTION'=>'Громкость notification 0-7 (notification) Уведомления','_CONFIG_TYPE'=>'num'),
        'info_audio_ring'=>array('DESCRIPTION'=>'Громкость рингтон 0-7 (ring) Вызовы и уведомления','_CONFIG_TYPE'=>'num'),
        'info_audio_system'=>array('DESCRIPTION'=>'Громкость системная 0-7 (system) Вызовы уведомления','_CONFIG_TYPE'=>'num'),
        'info_audio_voice'=>array('DESCRIPTION'=>'Громкость разговора 0-5 (voice)','_CONFIG_TYPE'=>'num'),
//      'info_battery_charging'=>array('DESCRIPTION'=>'Состояние зарядки (connected disconnected)'),
        'batteryCharging'=>array('DESCRIPTION'=>'Состояние заряда батареи'),
        'info_battery_health'=>array('DESCRIPTION'=>'Здоровье батареи (good)'),
//      'info_battery_level'=>array('DESCRIPTION'=>LANG_DEVICES_BATTERY_LEVEL, 'ONCHANGE'=>'batteryLevelUpdated'),
        'batteryLevel'=>array('DESCRIPTION'=>LANG_DEVICES_BATTERY_LEVEL,'ONCHANGE'=>'batteryLevelUpdated'),
        'info_battery_status'=>array('DESCRIPTION'=>'Состояние батареи (ok)'),
        'info_battery_temperature'=>array('DESCRIPTION'=>'Температура батареи'),
        'info_battery_type'=>array('DESCRIPTION'=>'Тип батареи'),
        'info_battery_voltage'=>array('DESCRIPTION'=>'Напряжение батареи'),
        'info_call_status'=>array('DESCRIPTION'=>'Состояние вызова (connection disconnection ringing)'),
        'info_display_brightness'=>array('DESCRIPTION'=>'Регулировка уровня подсветки от 4 до 100','_CONFIG_TYPE'=>'num'),
        'info_display_mode'=>array('DESCRIPTION'=>'Установка режима подсветки (auto manual)','_CONFIG_TYPE'=>'select','_CONFIG_OPTIONS'=>'auto=Автоматический,manual=Ручной'),
        'info_display_status'=>array('DESCRIPTION'=>'Состояние дисплея Включен Выключен (true false)'),
        'display_status'=>array('DESCRIPTION'=>'Состояние дисплея Включен Выключен (0 - 1)','ONCHANGE'=>'displayToWake'),
        'info_display_timeOff'=>array('DESCRIPTION'=>'Установка времени работы подсветки на устройстве в сек','_CONFIG_TYPE'=>'num'),
        'info_general_BRAND'=>array('DESCRIPTION'=>'BRAND'),
        'info_general_MODEL'=>array('DESCRIPTION'=>'MODEL'),
        'info_general_network'=>array('DESCRIPTION'=>'network'),
        'info_general_SDK'=>array('DESCRIPTION'=>'SDK'),
        'info_memory_RAM_free'=>array('DESCRIPTION'=>'RAM_free'),
        'info_memory_RAM_total'=>array('DESCRIPTION'=>'RAM_total'),
        'info_sensors_light'=>array('DESCRIPTION'=>'Датчик света'),
        'info_sensors_proximity'=>array('DESCRIPTION'=>'Датчик приближения'),
        'info_speech_results'=>array('DESCRIPTION'=>'Голосовое сообщение текстом','_CONFIG_HELP'=>'SdThermostat'),
        'info_tts_status'=>array('DESCRIPTION'=>'Состояние говорилки'),
        'info_key_KEYCODE_VOLUME_DOWN'=>array('DESCRIPTION'=>'Кнопка вниз'),
        'info_key_KEYCODE_VOLUME_UP'=>array('DESCRIPTION'=>'Кнопка вверх'),
        'info_key_KEYCODE_BACK'=>array('DESCRIPTION'=>'Кнопка выключить'),
        ),
    'METHODS'=>array(
        'batteryLevelUpdated'=>array('DESCRIPTION'=>'Обновление зарядки батареи','_CONFIG_SHOW'=>0),
        'alertResponse'=>array('DESCRIPTION'=>'Ответ от «диалогов» приходит в JSON формате и публикуется в топике /info/alert/response','_CONFIG_SHOW'=>0),
        'comm'=>array('DESCRIPTION'=>'cmd','_CONFIG_SHOW'=>0),
        //'saySpeech'=>array('DESCRIPTION'=>'Сообщение для Алисы голосовое','_CONFIG_SHOW'=>0),
        //'ttsRequest'=>array('DESCRIPTION'=>'Отправить текст в речь [строка] через comm_tts_request','_CONFIG_SHOW'=>0),
        //'ttsRequestAll'=>array('DESCRIPTION'=>'Отправить текст в речь [строка] через all_devices_tts_request','_CONFIG_SHOW'=>0),
        //'ttsStop'=>array('DESCRIPTION'=>'Остановить речь [логическое]','_CONFIG_SHOW'=>1),
        //'callEnd'=>array('DESCRIPTION'=>'Отклонить вызов [логическое] Завершить разговор','_CONFIG_SHOW'=>1),
        //'callNumber'=>array('DESCRIPTION'=>'Позвонить по номеру [номер]','_CONFIG_SHOW'=>0),
        //'switchDisplayMode'=>array('DESCRIPTION'=>'Тип подсветки автоматический или ручной [логический] (auto manual)','_CONFIG_SHOW'=>1),
        //'displayToWake'=>array('DESCRIPTION'=>'Вывести устройство из спящего режима [логическое] 0/1','_CONFIG_SHOW'=>0),
        //'displayTimeOff'=>array('DESCRIPTION'=>'Установите время подсветки [число] (сек)','_CONFIG_SHOW'=>0),
        //'home'=>array('DESCRIPTION'=>'На основной экран (1)','_CONFIG_SHOW'=>1),
        'getJson'=>array('DESCRIPTION'=>'Запросить через GET','_CONFIG_SHOW'=>1),
        'setJson'=>array('DESCRIPTION'=>'Запросить через GET','_CONFIG_SHOW'=>1),
        //'notiDelete'=>array('DESCRIPTION'=>'Удалить все уведомления [логическое]','_CONFIG_SHOW'=>1),
        'locationJson'=>array('DESCRIPTION'=>'Разбор массива геоданных [json]','_CONFIG_SHOW'=>0),
        //'switch'=>array('DESCRIPTION'=>'Пареключить','_CONFIG_SHOW'=>1),
        //'turnOn'=>array('DESCRIPTION'=>LANG_DEVICES_TURN_ON,'_CONFIG_SHOW'=>1),
        //'turnOff'=>array('DESCRIPTION'=>LANG_DEVICES_TURN_OFF,'_CONFIG_SHOW'=>1),
        //'voiceOn'=>array('DESCRIPTION'=>LANG_DEVICES_TURN_ON,'_CONFIG_SHOW'=>1),
        //'voiceOff'=>array('DESCRIPTION'=>LANG_DEVICES_TURN_OFF,'_CONFIG_SHOW'=>1),
    ),
//    'INJECTS'=>array(
//        'OperationalModes'=>array(
//            'System.stateChanged'=>'SXiGatewayRGB_injects',
//            'Communication.stateChanged'=>'SXiGatewayRGB_injects',
//            'NobodyHomeMode.modeChanged'=>'SXiGatewayRGB_injects',
//            'DarknessMode.modeChanged'=>'SXiGatewayRGB_injects',
//        ),
//    )
);
